### PR TITLE
code refactoring

### PR DESCRIPTION
**Pull request by sunnamed434**
this is will not play really big things, but may can be more readable for _other_

### CODE REVIEW

**Comment by sunnamed434** [comment]
There is no _Views_ changes, only Controllers or other tools/extensions changes

**Review by RestoreMonarchy — COMMENTED** [review]
Hi,
I have reviewed your pull request and made some changes to it.

* I didn't like using `Path.AltDirectorySeparatorChar` instead of just `/` char, so I changed it back
* I went further with your refactoring in url building and in the whole DiscordService I use BaseUrl service instead of passing baseUrl as a parameter from controller
* I removed your argument null checks in the controllers constructors, because dependency injection takes care of it

I created a merge request to development branch https://github.com/UnturnedStore/UnturnedStore/pull/26

**Comment by negrifelipe** [comment]
There is a problem with this pr @RestoreMonarchy. Here https://github.com/UnturnedStore/UnturnedStore/blob/f7d1e0ca87f1937555c0bf3ae798b8298c97475c/src/Website/Server/Controllers/ProductsController.cs#L263 there the controller should return because the user is unauthorized, previously it did but now with this pr it doesnt

**Comment by Pustalorc** [comment]
Merged to master with #27

**Pull request closed without merging**
