### PR TITLE
Disable html tags for products page

### PR DESCRIPTION
**Pull request by HathHub**

### CODE REVIEW

**Comment by RestoreMonarchy** [comment]
Why? :)

**Comment by HathHub** [comment]
xss

**Comment by Trojaner** [comment]
i dont think xss is possible because markdown shouldnt support script tags

**Comment by RestoreMonarchy** [comment]
Moderation team looks after that if they catch the seller using cross-site scripting they will ban and remove them from sellers.

We can't make this change, because it will break some product descriptions.

Yeah @Trojaner is right, the <script> tag won't even work

**Comment by HathHub** [comment]
image
Well, sadly it does accept script tags

**Comment by RestoreMonarchy** [comment]
> image Well, sadly it does accept script tags

ban-button

**Comment by Trojaner** [comment]
let me guess, its an iframe and not script running in the context of unturnedstores window?

**Comment by HathHub** [comment]
no
image
iframes wont allow xss

**Comment by Trojaner** [comment]
🤷 

maybe report to markdig: https://github.com/xoofx/markdig/

**Comment by HathHub** [comment]
what can be done is create an extension for https://github.com/UnturnedStore/UnturnedStore/blob/27e431b994be5f333f6e8db6f5749feeefc9d7b6/src/Website/Components/Helpers/MarkdownHelper.cs#L14, loop through every HtmlRenderer of the tab content and if check if it contains a script tag, should be the same process for inline tags, sanitizing the html with the library suggested twice still seems easier

**Comment by RestoreMonarchy** [comment]
> what can be done is create an extension for
> 
> https://github.com/UnturnedStore/UnturnedStore/blob/27e431b994be5f333f6e8db6f5749feeefc9d7b6/src/Website/Components/Helpers/MarkdownHelper.cs#L14
> , loop through every HtmlRenderer of the tab content and if check if it contains a script tag, should be the same process for inline tags, sanitizing the html with the library suggested twice still seems easier

How would you do that without removing the <script> tags which could be a part of the xml configurations for example? string replace won't work here, I thought we could use the library someone mentioned in one of the issues you sent

https://github.com/mganss/HtmlSanitizer

**Comment by HathHub** [comment]
That's true, either way sanitizing the output will be the way to go

**Comment by HathHub** [comment]
```cs
using Markdig;
using Ganss.XSS; 

namespace Website.Components.Helpers
{
    public class MarkdownHelper
    {
        public static string ParseToHtml(string markdown, bool disableHtml = true)
        {
            if (string.IsNullOrEmpty(markdown))
            {
                return string.Empty;
            }

            MarkdownPipelineBuilder builder = new MarkdownPipelineBuilder()
                    .UseEmojiAndSmiley()
                    .UseSoftlineBreakAsHardlineBreak()
                    .UseAdvancedExtensions()
                    .UseAutoLinks();

            if (disableHtml)
                builder.DisableHtml();

            string html = Markdown.ToHtml(markdown, builder.Build());

            if (disableHtml)
            {
                // Sanitize HTML using HtmlSanitizer
                var sanitizer = new HtmlSanitizer();
                html = sanitizer.Sanitize(html);
            }

            return html;
        }
    }
}

```

Something like this should fix the issue

**Comment by RestoreMonarchy** [comment]
Yeah testing it now

**Comment by RestoreMonarchy** [comment]
`!disableHtml` tho 😉 
```cs
if (!disableHtml)
{
    HtmlSanitizer sanitizer = new HtmlSanitizer();
    sanitizer.Sanitize(html);
}
```

**Comment by HathHub** [comment]
True! hope it gets fixed soon, this was reported the 20th of last month and seeing I got no response, contacted Pustalorc and told me to pr it right away.

**Comment by Bradler26** [comment]
Apologies for not receiving a response it seems Ed missed the DM. In future feel free to DM me directly for anything urgent (bradler) on discord.

Thanks again for the report!

**Pull request merged**
